#!/bin/sh

set -e

[ -f /etc/default/moira-notifier ] && . /etc/default/moira-notifier

startMoiraNotifier() {
  if [ -x /bin/systemctl ]; then
    /bin/systemctl daemon-reload
    /bin/systemctl start moira-notifier
  elif [ -x "/etc/init.d/moira-notifier" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
      invoke-rc.d moira-notifier start || true
    else
      /etc/init.d/moira-notifier start || true
    fi
  fi
}

case "$1" in
  configure)
  if ! getent group "moira" > /dev/null 2>&1 ; then
    addgroup --system "moira" --quiet
  fi
  if ! id moira > /dev/null 2>&1 ; then
    adduser --system --home /usr/share/grafana --no-create-home \
      --ingroup "moira" --disabled-password --shell /bin/false \
      "moira"
  fi

  # Set user permissions on /var/log/grafana, /var/lib/grafana
  mkdir -p /var/log/moira/notifier /var/lib/moira
	chown -R moira:moira /var/log/moira /var/lib/moira
	chmod 755 /var/log/moira /var/log/moira/notifier /var/lib/moira

	# configuration files should not be modifiable by grafana user, as this can be a security issue
	chown -Rh root:moira /etc/moira/*
	chmod 755 /etc/moira
	find /etc/moira -type f -exec chmod 640 {} ';'
	find /etc/moira -type d -exec chmod 755 {} ';'

	# this is a fresh installation
	elif [ -z $2 ] ; then
        if [ -x /bin/systemctl ] ; then
            echo "### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd"
            echo " sudo /bin/systemctl daemon-reload"
            echo " sudo /bin/systemctl enable grafana-server"
            echo "### You can start grafana-server by executing"
            echo " sudo /bin/systemctl start grafana-server"

        elif [ -x /usr/sbin/update-rc.d ] ; then
            echo "### NOT starting grafana-server by default on bootup, please execute"
            echo " sudo update-rc.d grafana-server defaults 95 10"
            echo "### In order to start grafana-server, execute"
            echo " sudo service grafana-server start"
        fi
	fi
	;;
esac
