#!/bin/sh

set -e

startMoiraCache() {
  if [ -x /bin/systemctl ]; then
    /bin/systemctl daemon-reload
    /bin/systemctl start moira-cache
  elif [ -x "/etc/init.d/moira-cache" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
      invoke-rc.d moira-cache start || true
    else
      /etc/init.d/moira-cache start || true
    fi
  fi
}

case "$1" in
  configure)
    if ! getent group "moira" > /dev/null 2>&1 ; then
      addgroup --system "moira" --quiet
    fi
    if ! id moira > /dev/null 2>&1 ; then
      adduser --system --home /usr/share/moira --no-create-home \
        --ingroup "moira" --disabled-password --shell /bin/false \
        "moira"
    fi

    mkdir -p /var/log/moira/cache
    chown -R moira:moira /var/log/moira
    chmod 755 /var/log/moira /var/log/moira/cache

    chown -Rh root:moira /etc/moira/*
    chmod 755 /etc/moira
    find /etc/moira -type f -exec chmod 640 {} ';'
    find /etc/moira -type d -exec chmod 755 {} ';'

    # this is a fresh installation
    elif [ -z $2 ] ; then
      if [ -x /bin/systemctl ] ; then
        /bin/systemctl daemon-reload
        /bin/systemctl enable moira-cache
      elif [ -x /usr/sbin/update-rc.d ] ; then
        update-rc.d moira-cache defaults 95 10
      fi
    fi
  ;;
esac
