#!/bin/sh

set -e

startMoiraNotifier() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
    /bin/systemctl start moira-notifier.service
  elif [ -x /etc/init.d/moira-notifier ] ; then
    /etc/init.d/moira-notifier start
  elif [ -x /etc/rc.d/init.d/moira-notifier ] ; then
    /etc/rc.d/init.d/moira-notifier start
  fi
}

stopMoiraNotifier() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl stop moira-notifier.service > /dev/null 2>&1 || :
  elif [ -x /etc/init.d/moira-notifier ] ; then
    /etc/init.d/moira-notifier stop
  elif [ -x /etc/rc.d/init.d/moira-notifier ] ; then
    /etc/rc.d/init.d/moira-notifier stop
  fi
}

# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
  if ! getent group "moira" > /dev/null 2>&1 ; then
    groupadd -r "moira"
  fi
  if ! getent passwd "moira" > /dev/null 2>&1 ; then
    useradd -r -g moira -d /usr/share/moira -s /sbin/nologin \
      -c "Moira user" moira
  fi

  mkdir -p /var/log/moira/notifier
  chown -R moira:moira /var/log/moira/notifier
  chmod 755 /var/log/moira/notifier

  chown -Rh root:moira /etc/moira/*
  chmod 755 /etc/moira
  find /etc/moira -type f -exec chmod 640 {} ';'
  find /etc/moira -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
    /bin/systemctl enable moira-notifier.service
  elif [ -x /sbin/chkconfig ] ; then
    /sbin/chkconfig --add moira-notifier
  fi
elif [ $1 -ge 2 ] ; then
  stopMoiraNotifier
  startMoiraNotifier
fi
