redis:
  host: localhost
  port: 6379

worker:
  log_dir: /var/log/moira/worker

api:
  port: 8080
  listen: 127.0.0.1

graphite:
  uri: localhost
  prefix: DevOps.moira
  interval: 60

checker:
  nodata_check_interval: 60

front:
  uri: http://localhost

notifier:
  log_file: /var/log/moira/notifier/notifier.log
  log_level: info
  log_color: false
  sender_timeout: 10s0ms
  resending_timeout: 24:00 # 24 hours
  senders:
    - type: mail
      mail_smtp_host: smtp.example.com
      mail_smtp_port: 25
      mail_from: moira@example.com
      mail_insecure_tls: true
#    - type: slack
#      api_token:
#    - type: pushover
#      api_token:
#    - type: telegram
#      api_token: 
#    - type: script
#      name: mymail
#      exec: /bin/echo 123

cache:
  log_file: /var/log/moira/cache/cache.log
  listen: ":2003"
  retention-config: /etc/moira/cache/storage-schemas.conf
  pid: /var/run/moira-cache.pid
